workspace:
  base: /go

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER"

  latest:
    image: docker
    storage_driver: overlay
    repo: plugins/docker
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

  develop:
    image: docker
    storage_driver: overlay
    repo: plugins/docker
    tags: [ "develop" ]
    when:
      branch: develop
      event: push

plugin:
  name: Docker
  desc: Build and publish images to a Docker registry
  type: publish
  image: plugins/docker
  labels:
    - docker
    - image
    - container
